# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: true
contact_links:
  - name: Scoop Community Support
    url: https://github.com/ScoopInstaller/Scoop/discussions
    about: For general Scoop questions (not specific to this bucket).
  - name: TuringRiff-bucket Issues
    url: https://github.com/TuringRiff/TuringRiff-bucket/issues
    about: For issues specific to apps in this bucket.
